export const ASSETS = {
  strip: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-01.png",
  couple: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-02.png",
  calendarIcon: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-03.png",
  clockIcon: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-04.png",
  pinIcon: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-05.png",
  tagLeft: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-06.png",
  tagRight: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-07.png",
  openMapBtn: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-08.png",
  titleDatePlace: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-09.png",
  titleOurStory: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-10.png",
  titleDressCode: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-11.png",
  titleAttendance: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-12.png",
  titleBlessings: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-13.png",
  titleWeddingGift: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-14.png",
  titleRsvp: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-15.png",
  timelineHeart: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-16.png",
  timelineFlowers: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-17.png",
  timelineRings: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-18.png",
  dressCodeAttire: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-19.png",
  timelineLine: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-20.png",
  inputBorder: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-21.png",
  btnConfirmPresence: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-22.png",
  btnSubmitBlessing: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-23.png",
  cardContainer: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-24.png",
  rsvpArch: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-25.png?v=3",
  topRings: "https://cdn.serastory.com/undangan/templates/illustrated-love-story-01/01-26.png",
};
